#!/usr/bin/env ruby

# Take output of grep and open all filenames in TextMate.
# grep -ri 'TextMate' . | gmate

flag   = ARGV.first
input  = ARGV.last || STDIN.read
binary = flag == '-r' ? 'rmate' : 'mate'

files = input.scan(/^([^:]+):/).each_with_object([]) do |match, list|
  list << match.first
end.uniq!

system "#{binary} #{files.join(' ')}" if files
